backend:
  name: git-gateway

media_folder: images/uploads

collections:
  - name: blog
    label: Blog
    folder: content/blog
    create: true
    slug: index
    path: '{{title}}'
    editor:
      preview: true
    fields:
      - { label: Title, name: title, widget: string }
      - { label: Publish Date, name: date, widget: datetime }
      - { label: Body, name: body, widget: markdown }

  - label: Pages
    name: pages
    files:
      - label: Home
        name: home
        file: content/home.md
        fields:
          - { label: Body, name: body, widget: markdown }
      - label: Resume
        name: resume
        file: content/resume.md
        fields:
          - { label: Body, name: body, widget: markdown }
