backend:
  name: git-gateway

media_folder: static/images/uploads
public_folder: /images/uploads

collections:
  - name: blog
    label: Blog
    folder: content/blog
    create: true
    slug: '{{title}}'
    path: 'blog/{{title}}'
    editor:
      preview: true
    fields:
      - { label: Title, name: title, widget: string }
      - { label: Publish Date, name: date, widget: datetime }
      - { label: Body, name: body, widget: markdown }

  - label: Pages
    name: pages
    files:
      - label: Home
        name: home
        file: content/pages/home.md
        fields:
          - { label: Image, name: image, widget: file }
          - { label: Body, name: body, widget: markdown }
      - label: Resume
        name: resume
        file: content/pages/resume.md
        fields:
          - { label: Image, name: image, widget: file }
          - { label: Body, name: body, widget: markdown }
